services:
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd-server
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 5s
      timeout: 5s
      retries: 3

  distributor-server:
    build:
      context: .
    container_name: distributor-server
    depends_on:
      etcd:
        condition: service_healthy
    environment:
      - ETCD_ENDPOINTS=etcd:2379
    ports:
      - "50051:50051"
    command: ["-mode=server", "-etcd=etcd:2379", "-shards=20"]
    healthcheck:
      test: ["CMD", "shard-distributor", "-mode=healthcheck", "-server=localhost:50051"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  client1:
    build:
      context: .
    container_name: client1
    depends_on:
      distributor-server:
        condition: service_healthy
    environment:
      - SERVER_ADDR=distributor-server:50051
    command: ["-mode=client", "-id=instance-1", "-server=distributor-server:50051", "-duration=60s"]

  client2:
    build:
      context: .
    container_name: client2
    depends_on:
      distributor-server:
        condition: service_healthy
    environment:
      - SERVER_ADDR=distributor-server:50051
    command: ["-mode=client", "-id=instance-2", "-server=distributor-server:50051", "-duration=60s"]

  client3:
    build:
      context: .
    container_name: client3
    depends_on:
      distributor-server:
        condition: service_healthy
    environment:
      - SERVER_ADDR=distributor-server:50051
    command: ["-mode=client", "-id=instance-3", "-server=distributor-server:50051", "-duration=60s"]
